### ISSUE TITLE
.parse-names won't exist in 6.e language

### ISSUE THREAD

**Issue by zoffixznet** [spitsh/spitsh#6]
The `parse-names` is now named `uniparse`, as of Rakudo version 2017.12-10-ge5c38ad

The original `parse-names` will continue to work for some time. It will issue a deprecation warning when 6.d language will be released (around first half of 2018) and will be removed entirely in 6.e language.

More info: https://github.com/perl6/doc/commit/bff42f80b1

**Comment by LLFourn** [comment]
Fixed. Thanks Zoffix!
